language: java
before_install:
  - chmod +x gradlew
install: true
script: "./gradlew build -x copyDistFiles"
            -./gradlew check
branches:
  only: master
matrix:
  include:
       - language: java
        jdk: oraclejdk8
                  script:
                    - ./mvnw test -B -q
                  before_script:
                    - cd ./backend/