language: java
before_install:
  - chmod +x gradlew
install: true
script: "./gradlew build -x copyDistFiles"
            -./gradlew check
# whitelist
branches:
  only:
    - master
    - stable
matrix:
  include:
       - language: java
        jdk: oraclejdk8
                  script:
                    - ./mvnw test -B -q
                  before_script:
                    - cd ./backend/